"""ABI surface alignment — bindgen as the source of truth for exported shims.

cando2's value.spec is generated by running bindgen over the C headers
(forclift/producers/headers.py); the replay harness calls our cdylib with
those ABI-exact types. Our FFI shims were generated from tree-sitter
signatures read off the .c file — any drift (wrong scalar width, pointer vs
value, arity) is undefined behavior at replay, not a clean failure.

This module runs the SAME bindgen invocation over the C tree and compares
each exported shim against bindgen's decl at the ABI level:

- arity must match,
- scalar params/returns must have the same width class (c_int vs c_long ...),
- pointer params match ANY pointer on our side (all data pointers share one
  ABI; our opaque `*mut c_void` handles are fine against `*mut git_oid`),
- fn-pointer (callback) params are flagged — marshaling them needs a
  trampoline and the symbol is outside cando2 amenability anyway.

Bindgen failing (missing binary, headers that don't compile standalone) is an
honest degradation: `abi_decls` returns {} and callers fall back to the
tree-sitter signature, exactly as before this module existed.

CLI:  python3 -m rustgen.surface out/tree-cache --c-root <tree> \
          [--clang-args "-DGIT_SHA1_BUILTIN ..."]
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

# --------------------------------------------------------------------------- #
# bindgen invocation
# --------------------------------------------------------------------------- #

def discover_include_dirs(c_root: Path) -> list[Path]:
    """include/ plus every directory under src/ that holds headers directly
    (src/libgit2, src/util, ... — internal headers include each other bare)."""
    dirs = []
    inc = c_root / "include"
    if inc.is_dir():
        dirs.append(inc)
    src = c_root / "src"
    roots = [src] if src.is_dir() else [c_root]
    for root in roots:
        if root.is_dir():
            for d in sorted({p.parent for p in root.rglob("*.h")}):
                dirs.append(d)
    return dirs or [c_root]


def run_bindgen(c_root: Path, wrapper_includes: list[str], out_dir: Path,
                clang_args: str = "", bindgen_bin: str = "bindgen",
                allow: str | None = None) -> Path | None:
    """bindgen over a wrapper that includes `wrapper_includes` (bare names,
    resolved via the discovered -I dirs) -> out_dir/bindings.rs, or None.
    `allow` overrides the allowlist-file regex (default: the whole tree)."""
    if not wrapper_includes:
        return None
    out_dir.mkdir(parents=True, exist_ok=True)
    wrapper = out_dir / "_wrapper.h"
    wrapper.write_text("".join(f'#include "{h}"\n' for h in wrapper_includes))
    out = out_dir / "bindings.rs"
    if allow is None:
        allow = re.escape(str(c_root).rstrip("/")) + r"/.*"
    cmd = [bindgen_bin, "--allowlist-file", allow, "--no-layout-tests",
           "--no-doc-comments", str(wrapper), "-o", str(out), "--"]
    cmd += [f"-I{d}" for d in discover_include_dirs(c_root)]
    cmd += clang_args.split()
    try:
        res = subprocess.run(cmd, capture_output=True, text=True)
    except OSError:
        return None
    if res.returncode != 0 or not out.is_file() or out.stat().st_size == 0:
        return None
    return out


def header_for_source(c_root: Path, source_name: str) -> str | None:
    """The bare header name declaring `foo.c`'s functions (foo.h somewhere in
    the tree), if one exists."""
    want = Path(source_name).stem + ".h"
    for p in c_root.rglob(want):
        return want
    return None


# --------------------------------------------------------------------------- #
# decl extraction (paren-depth-aware — callback params contain inner () / ->)
# --------------------------------------------------------------------------- #

_FN_HEAD = re.compile(r"(?:pub\s+)?(?:unsafe\s+)?(?:extern\s+\"C\"\s+)?fn\s+(\w+)\s*\(")


def _scan_fn(text: str, start: int) -> tuple[str, str, str] | None:
    """(name, params, ret) for the fn head starting at `start`."""
    m = _FN_HEAD.match(text, start)
    if not m:
        return None
    depth = 0
    for j in range(m.end() - 1, len(text)):
        if text[j] == "(":
            depth += 1
        elif text[j] == ")":
            depth -= 1
            if depth == 0:
                params = text[m.end():j]
                rest = text[j + 1:j + 200].lstrip()
                ret = ""
                if rest.startswith("->"):
                    ret = rest[2:].split(";", 1)[0].split("{", 1)[0].strip()
                return m.group(1), params, ret
    return None


def fn_decls(rust_src: str) -> dict[str, tuple[list[str], str]]:
    """{name: ([param types], ret type)} for every fn decl/def in rust_src."""
    out: dict[str, tuple[list[str], str]] = {}
    for m in _FN_HEAD.finditer(rust_src):
        got = _scan_fn(rust_src, m.start())
        if not got:
            continue
        name, params, ret = got
        out[name] = (_split_params(params), ret)
    return out


def _split_params(params: str) -> list[str]:
    """Top-level comma split of a param list; returns the TYPE of each param
    (text after the top-level ':'), skipping doc/attr noise."""
    # `-> ret` inside callback types would decrement '>' depth — neutralize
    params = params.replace("->", "→")
    parts, depth, buf = [], 0, []
    for ch in params:
        if ch in "(<[":
            depth += 1
        elif ch in ")>]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
    if "".join(buf).strip():
        parts.append("".join(buf))
    types = []
    for p in parts:
        seg, d = p, 0
        # type = text after the first top-level ':'
        for i, ch in enumerate(p):
            if ch in "(<[":
                d += 1
            elif ch in ")>]":
                d -= 1
            elif ch == ":" and d == 0:
                seg = p[i + 1:]
                break
        types.append(" ".join(seg.split()))
    return types


# --------------------------------------------------------------------------- #
# ABI classification + comparison
# --------------------------------------------------------------------------- #

_SCALAR_ALIASES = {
    "c_char": "i8", "c_schar": "i8", "c_uchar": "u8",
    "c_short": "i16", "c_ushort": "u16",
    "c_int": "i32", "c_uint": "u32",
    "c_long": "i64", "c_ulong": "u64",
    "c_longlong": "i64", "c_ulonglong": "u64",
    "c_size_t": "usize", "c_ssize_t": "isize", "size_t": "usize",
    "c_float": "f32", "c_double": "f64",
}


def abi_class(ty: str) -> str:
    """ABI equivalence class of a Rust type as it crosses extern "C":
    'ptr' (any data pointer/reference), 'fnptr', a normalized scalar name,
    'void', or 'other:<ty>'."""
    t = ty.strip()
    for p in ("::std::os::raw::", "std::os::raw::", "::core::ffi::",
              "core::ffi::", "::libc::", "libc::", "::std::ffi::", "std::ffi::"):
        t = t.replace(p, "")
    t = t.strip()
    if not t or t == "()":
        return "void"
    if re.match(r"(\*const|\*mut|&)", t):
        return "ptr"
    if "fn(" in t or t.startswith("Option < unsafe") or "unsafe extern" in t:
        return "fnptr"
    leaf = t.split("::")[-1].strip()
    if leaf in _SCALAR_ALIASES:
        return _SCALAR_ALIASES[leaf]
    if re.fullmatch(r"[iu](8|16|32|64|128)|[iu]size|f32|f64|bool", leaf):
        return leaf
    # bindgen type aliases (git_object_size_t etc.) — unknown here; the shim
    # side never uses them, so this only appears on the bindgen side
    return f"other:{leaf}"


def compare_decl(shim: tuple[list[str], str],
                 abi: tuple[list[str], str]) -> list[str]:
    """Mismatch descriptions between our shim decl and bindgen's (empty=OK)."""
    problems = []
    s_params, s_ret = shim
    a_params, a_ret = abi
    if len(s_params) != len(a_params):
        problems.append(f"arity {len(s_params)} != ABI {len(a_params)}")
        return problems
    for i, (s, a) in enumerate(zip(s_params, a_params)):
        cs, ca = abi_class(s), abi_class(a)
        if ca == "fnptr":
            if cs not in ("fnptr", "ptr"):
                problems.append(f"param {i}: callback expected, shim has {s}")
            continue
        if ca.startswith("other:"):
            # typedef'd integer (e.g. git_time_t) — accept any scalar of
            # pointer width or smaller only if it IS a scalar
            if cs == "ptr":
                problems.append(f"param {i}: ABI scalar {a} vs shim pointer {s}")
            continue
        if cs != ca:
            problems.append(f"param {i}: shim {s} ({cs}) != ABI {a} ({ca})")
    cs, ca = abi_class(s_ret), abi_class(a_ret)
    if not ca.startswith("other:") and cs != ca:
        problems.append(f"return: shim {s_ret} ({cs}) != ABI {a_ret} ({ca})")
    return problems


def abi_decls(c_root: Path, source_name: str, clang_args: str = "",
              bindgen_bin: str = "bindgen") -> dict[str, tuple[list[str], str]]:
    """Bindgen decls for the header matching `source_name` (plus the public
    umbrella as fallback coverage). {} on any failure — caller falls back."""
    includes = []
    own = header_for_source(c_root, source_name)
    if own:
        includes.append(own)
    inc = c_root / "include"
    if inc.is_dir():
        includes += sorted(p.name for p in inc.glob("*.h"))
    with tempfile.TemporaryDirectory() as td:
        out = run_bindgen(c_root, includes, Path(td), clang_args, bindgen_bin)
        if out is None and own:  # own header may not compile standalone
            out = run_bindgen(c_root, includes[1:], Path(td), clang_args, bindgen_bin)
        if out is None:
            return {}
        return fn_decls(out.read_text(errors="replace"))


def extern_decl_rust(name: str, decl: tuple[list[str], str]) -> str | None:
    """A compilable `pub fn name(...) -> ...;` extern decl for a crate that
    has NONE of the C types: struct pointers become c_void pointers (same
    ABI), scalars keep their class. None when the decl can't be mapped
    soundly (by-value struct/typedef of unknown width, callbacks)."""
    def map_ty(t: str) -> str | None:
        if t.strip() == "...":
            return "..."  # C variadic — legal in Rust extern "C" decls
        c = abi_class(t)
        if c == "ptr":
            mut = "*mut" if t.strip().startswith("*mut") else "*const"
            inner = re.sub(r"^\*(const|mut)\s+", "", t.strip())
            if re.fullmatch(r"[iu](8|16|32|64|128)|[iu]size|f32|f64|bool",
                            abi_class(inner)):
                return t  # pointer to scalar — keep as-is
            return f"{mut} core::ffi::c_void"
        if c in ("fnptr",) or c.startswith("other:"):
            return None
        if c == "void":
            return "()"
        return c  # normalized scalar (i32, usize, ...)

    params, ret = decl
    mapped = [map_ty(t) for t in params]
    ret_m = map_ty(ret) if ret.strip() else "()"
    if any(m is None for m in mapped) or ret_m is None:
        return None
    args = ", ".join("..." if t == "..." else f"a{i}: {t}"
                     for i, t in enumerate(mapped))
    tail = f" -> {ret_m}" if ret_m != "()" else ""
    return f"pub fn {name}({args}){tail};"


def render_abi_decl(name: str, decl: tuple[list[str], str]) -> str:
    params, ret = decl
    args = ", ".join(f"a{i}: {t}" for i, t in enumerate(params))
    return f"fn {name}({args})" + (f" -> {ret}" if ret and ret != "()" else "")


# --------------------------------------------------------------------------- #
# CLI: drift report for an assembled crate
# --------------------------------------------------------------------------- #

def drift_report(lib_rs: str, decls: dict[str, tuple[list[str], str]],
                 exported: list[str]) -> dict[str, list[str] | None]:
    """{symbol: None (no ABI decl found) | [] (aligned) | [problems]}."""
    shims = fn_decls(lib_rs)
    report: dict[str, list[str] | None] = {}
    for sym in exported:
        if sym not in decls:
            report[sym] = None
        elif sym not in shims:
            report[sym] = ["exported but no shim decl parsed from lib.rs"]
        else:
            report[sym] = compare_decl(shims[sym], decls[sym])
    return report


def main() -> None:
    import argparse
    import json

    ap = argparse.ArgumentParser(description="shim-vs-bindgen ABI drift report")
    ap.add_argument("out_dir", type=Path)
    ap.add_argument("--c-root", type=Path, required=True)
    ap.add_argument("--clang-args", default="")
    args = ap.parse_args()

    from state import Store
    store = Store.load(args.out_dir)
    source_name, exported = "?", []
    for r in store.records:
        if r.get("type") == "event" and r.get("event") == "start":
            source_name = r.get("file", "?")
        elif r.get("type") == "rust_ffi":
            exported = r.get("exported", [])
    lib_rs = (args.out_dir / "rust_crate" / "src" / "lib.rs").read_text()

    decls = abi_decls(args.c_root, source_name, args.clang_args)
    if not decls:
        print(f"[surface] {args.out_dir.name}: bindgen unavailable/failed — no report")
        return
    report = drift_report(lib_rs, decls, exported)
    n_ok = sum(1 for v in report.values() if v == [])
    n_missing = sum(1 for v in report.values() if v is None)
    drifted = {k: v for k, v in report.items() if v}
    print(f"[surface] {args.out_dir.name}: {n_ok}/{len(report)} aligned, "
          f"{n_missing} without ABI decl, {len(drifted)} drifted")
    for sym, problems in drifted.items():
        for p in problems:
            print(f"  DRIFT {sym}: {p}")


if __name__ == "__main__":
    main()
